general:
  # Valid log levels: OFF, SEVERE, WARNING, INFO, DEBUG, FINE
  # DEBUG and FINE are equivalent and both enable debug logging
  # Default: INFO
  logLevel: INFO

lore:
  nearbyRadius: 50.0
  requireApproval: true
  handlers:
    GENERIC: DEFAULT
    PLAYER: DEFAULT
    CITY: DEFAULT
    LANDMARK: DEFAULT
    FACTION: DEFAULT
    PATH: DEFAULT
    ITEM: DEFAULT
    EVENT: DEFAULT
    QUEST: DEFAULT
    ENCHANTMENT: DEFAULT
    HEAD: DEFAULT
    PLAYER_HEAD: DEFAULT
    MOB_HEAD: DEFAULT
    HAT: DEFAULT  

storage:
  test-mode: no # yes = wipe schema on start, no = keep tables on start
  type: sqlite
  mysql:
    host: localhost
    port: 3306
    username: root
    password: ''
    useSSL: false
    database: 
    tablePrefix: 
  sqlite:
    database: data.db
messages:
  generic:
    error:
    - '[Error]'
    success:
    - '[Success]'
    info:
    - '[Info]'
    help:
    - '[Help]'
    no_held_item:
    - 'You must be holding an item!'
