name: RVNKLore
api: "1.17"
version: 1.0.0
description: A lore data system for Minecraft
authors: [Derek, Fourz] 
main: org.fourz.RVNKLore.RVNKLore
api-version: 1.17

commands:
  lore:
    description: Main command for RVNKLore plugin
    usage: /lore <subcommand> [args...]

permissions:
  rvnklore.*:
    description: Gives access to all RVNKLore commands
  rvnklore.admin:
    description: Gives access to administrative commands
    default: op
    children: {}
  rvnklore.command.*:
    description: Gives access to all basic lore commands
  rvnklore.register.*:
    description: Gives access to all registration commands
  rvnklore.command.add:
    description: Allows adding new lore entries
  rvnklore.command.get:
    description: Allows viewing lore entries
  rvnklore.command.list:
    description: Allows listing lore entries
  rvnklore.command.getitem:
    description: Allows getting lore items
    default: op
  rvnklore.register.city:
    description: Allows registering new cities
  rvnklore.sign.landmark:
    description: Allows players to create landmark signs
    default: op
  rvnklore.approve.own:
    description: Allows players to auto-approve their own submissions
    default: op
  rvnklore.admin.item.give:
    description: Allows giving any lore item via /lore item give
    default: op
  rvnklore.command.collection:
    description: Allows viewing and claiming collection progress and rewards
